name: llmzip-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - numpy=1.21.0
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - jupyter=1.0.0
  - ipython=7.31.0
  - tqdm=4.62.3
  - pip=21.3.1
  - pip:
    - transformers==4.18.0
    - datasets==2.6.1
    - sentencepiece==0.1.96
    - tokenizers==0.12.1
    - sacremoses==0.0.53
    - huggingface-hub==0.4.0
    - python-dotenv==0.19.2
    - nltk==3.6.7
    - spacy==3.2.0
    - gensim==4.1.2
    - regex==2022.3.15
    - requests==2.27.1
    - beautifulsoup4==4.10.0
    - lxml==4.8.0
    - pyyaml==6.0
    - joblib==1.1.0
    - cloudpickle==2.0.0
    - zlib==1.2.11
    - bitsandbytes==0.35.0
    - accelerate==0.12.0
    - einops==0.4.1
    - wandb==0.12.21
    - tensorboard==2.8.0
    - plotly==5.6.0
    - psutil==5.9.0
    - nvidia-ml-py3==7.352.0
