name: llmzip-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and scientific computing
  - python=3.10  
  - numpy=1.21.0
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.2

  # Visualization
  - matplotlib=3.5.1
  - seaborn=0.11.2

  # Jupyter and IPython
  - jupyter=1.0.0
  - ipython=7.31.0

  # Utilities
  - tqdm=4.62.3
  - pip=21.3.1

  # Additional packages installed via pip
  - pip:
    # Transformers and related libraries
    - transformers==4.18.0
    - datasets==2.6.1
    - sentencepiece==0.1.96
    - tokenizers==0.12.1
    - sacremoses==0.0.53
    - huggingface-hub==0.4.0

    # NLP tools
    - nltk==3.6.7
    - spacy==3.2.0
    - gensim==4.1.2

    # Utilities and helpers
    - python-dotenv==0.19.2
    - regex==2022.3.15
    - requests==2.27.1
    - beautifulsoup4==4.10.0
    - lxml==4.8.0
    - pyyaml==6.0
    - joblib==1.1.0
    - cloudpickle==2.0.0

    # Compression-related
    - zlib==1.2.11

    # Deep learning and optimization
    - bitsandbytes==0.35.0
    - accelerate==0.12.0
    - einops==0.4.1

    # Logging and visualization
    - wandb==0.12.21
    - tensorboard==2.8.0
    - plotly==5.6.0

    # System utilities
    - psutil==5.9.0
    - nvidia-ml-py3==7.352.0